### ISSUE TITLE
3.2 Fresh Install - Dependency Not Met

### ISSUE THREAD

**Issue by PocketSizedAnimations** [TrueCommerce/CloudFtpBridge#29]
Installed 3.2.0 (first time install) fresh onto a client's machine and Service failed to start
Error: Windows could not start the Cloud FTP Bridge service on Local Computer. 
Error 1053: The service did not respond to the start or control request in a timely fashion

- Tried to run via CMD prompt : via navigating to C:\Program Files\True Commerce\PSG Engineering\Cloud FTP Bridge and running cmd cloudftpbridge.blazorapp.exe
- Error: It was not possible to find any compatible framework version. The specified version of 'Microsoft.AspNetcore.App', version '5.0.0' was not found
- Installed latest ASP Core .NET
- Restarted machine
- Tried CMD again : 
- Error : It was not possible to find any compatible framework version, the specified framework 'Micrsoft.AspNetCore.App', Version 5.0.12 was not found
- Checked customers Add/Remove Features list - confirmed 5.0.12 Core was listed
- Removed CloudFTPBridge 3.2 | installed 3.1.2, no issues starting service

I'm not sure what was wrong, I'm assuming something silly - but per their setup 5.0.12 was properly installed but the service kept failing because it wouldn't find it. Simplest solution was to use an older version

I did notice however, that 3.1.2 was ~60mb while 3.2 was ~6mb. Not sure if the installer changed to a downloadable installer between versions, but significant difference in size was od
![CloudBridge_NetError](https://user-images.githubusercontent.com/35338622/144279156-daaa16a4-68f8-4803-b37c-0b2754a2a07b.png)
d.

**Comment by DotJoshJohnson** [comment]
This is a regression introduced in 3.2. Version 3.1.2 and below were distributed as self-contained apps that shipped with a copy of the runtime. When I moved to the automated build pipeline, I must have missed a compiler flag. I'll make sure that flag gets added back in for the 3.3 release.

**Comment by DotJoshJohnson** [comment]
In the meantime, by the way, installing the [ASP.NET Core Runtime Hosting Bundle](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-5.0.12-windows-hosting-bundle-installer) will resolve the error.
